// <auto-generated />
using ITI_Entities.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITI_Entities.Migrations
{
    [DbContext(typeof(ITI_Context))]
    [Migration("20260302105731_Department_Name_added_Required")]
    partial class Department_Name_added_Required
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseDepartment", b =>
                {
                    b.Property<int>("CoursesCrsID")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentsDeptID")
                        .HasColumnType("int");

                    b.HasKey("CoursesCrsID", "DepartmentsDeptID");

                    b.HasIndex("DepartmentsDeptID");

                    b.ToTable("CourseDepartment");
                });

            modelBuilder.Entity("ITI_Entities.Models.Course", b =>
                {
                    b.Property<int>("CrsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrsID"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CrsID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("ITI_Entities.Models.Course_Student", b =>
                {
                    b.Property<int>("CrsID")
                        .HasColumnType("int");

                    b.Property<int>("StdID")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CrsID", "StdID");

                    b.HasIndex("StdID");

                    b.ToTable("course_Students");
                });

            modelBuilder.Entity("ITI_Entities.Models.Department", b =>
                {
                    b.Property<int>("DeptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptID"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DeptID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ITI_Entities.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DeptID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DeptID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CourseDepartment", b =>
                {
                    b.HasOne("ITI_Entities.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesCrsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITI_Entities.Models.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentsDeptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ITI_Entities.Models.Course_Student", b =>
                {
                    b.HasOne("ITI_Entities.Models.Course", "Course")
                        .WithMany("course_Students")
                        .HasForeignKey("CrsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITI_Entities.Models.Student", "Student")
                        .WithMany("course_Students")
                        .HasForeignKey("StdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ITI_Entities.Models.Student", b =>
                {
                    b.HasOne("ITI_Entities.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DeptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ITI_Entities.Models.Course", b =>
                {
                    b.Navigation("course_Students");
                });

            modelBuilder.Entity("ITI_Entities.Models.Department", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("ITI_Entities.Models.Student", b =>
                {
                    b.Navigation("course_Students");
                });
#pragma warning restore 612, 618
        }
    }
}
